### ISSUE TITLE
apple clang 16 (at least) needs -fexperimental-library

### ISSUE THREAD

**Issue by andresailer** [root-project/veccore#27]
As far as I can tell building against veccore on apple clang 16 on macos needs -fexperimental-library

Otherwise there is going to be a lot of

```
/Users/sftnight/build/workspace/lcg_nightly_pipeline/install/veccore/0.8.1-f2b7a/arm64-mac14-clang160-opt/include/VecCore/Backend/SIMD.h:17:24: error: no member named 'experimental' in namespace 'std'
   17 | struct TypeTraits<std::experimental::simd_mask<T, Abi>> {
      |                   ~~~~~^
```

**Comment by couet** [comment]
Do you know how to install it?

**Comment by amadio** [comment]
You need to use `-std=c++20` if you want to use `std::simd`. Are you using it?

**Comment by andresailer** [comment]
It is just a flag that has to be exported like an `INTERFACE_COMPILE_OPTION`

Yes, I am using c++20 otherwise I wouldn't reach this code

https://github.com/root-project/veccore/blob/b4b2bf3d33d07caa2318fa0308cac03cb8718635/include/VecCore/Backend/SIMD.h#L4-L18

Right?

**Comment by andresailer** [comment]
Here is a simple reproducer, as long as you have a mac14 clang16 machine, I guess?

```
cat > test.cpp << EOF
#include <experimental/simd>
template <typename T, class Abi>
struct TypeTraits<std::experimental::simd_mask<T, Abi>> {
  using IndexType = typename std::experimental::simd_mask<T, Abi>::simd_type;
  using ScalarType = typename std::experimental::simd_mask<T, Abi>::value_type;
  static constexpr size_t Size = std::experimental::simd<T, Abi>::size();
};
int main() {
  return 0;
}
EOF

clang++ -std=c++20 test.cpp
clang++ -std=c++20 -fexperimental-library test.cpp
```

**Comment by andresailer** [comment]
Please look at the difference between with and without -fexperimental-library

**Comment by amadio** [comment]
```
gentoo ~ $ clang++ -std=c++20 test.cpp
test.cpp:3:8: error: explicit specialization of undeclared template struct 'TypeTraits'
    3 | struct TypeTraits<std::experimental::simd_mask<T, Abi>> {
      |        ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
gentoo ~ $ clang++ -std=c++20 -fexperimental-library test.cpp
test.cpp:3:8: error: explicit specialization of undeclared template struct 'TypeTraits'
    3 | struct TypeTraits<std::experimental::simd_mask<T, Abi>> {
      |        ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by amadio** [comment]
I will try on macOS, the above is on Linux, and with clang-18, so might explain the differences.

**Comment by amadio** [comment]
It might be easier if you give me access to one of your build nodes, I only have an old machine with macOS 11.7 available to me at the moment, and that has clang 13 installed.

**Comment by andresailer** [comment]
Continuing from our mattermost discussion, and since apple clang hopeless for now

Is it enough to add some logic so that VECCORE_ENABLE_STD_SIMD is not enabled in these cases?
```c++
 #if __cplusplus >= 202002L && defined(__has_include) 
 #if __has_include(<experimental/simd>) 
 #define VECCORE_ENABLE_STD_SIMD 
 #endif 
 #endif 
```

**Comment by amadio** [comment]
Yes, that is probably what I will do in the end.

**Comment by amadio** [comment]
Thanks, added to the release notes!
